config/routes.rb
Rails.application.routes.draw do
  resources :politicians
  resources :political_parties
  resources :states
  resources :assembly_constituencies
  resources :loksabha_constituencies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/political_party.rb
class Politicalparty
  include Mongoid::Document
  field :party_name, type: String
  field :party_symbol, type: String
  field :extra, type: String
  
  has_and_belongs_to_many :politicians, inverse_of :politician
end

app/controllers/political_parties_controller.rb
class PoliticalPartiesController < ApplicationController
  before_action :set_political_party, only: [:show, :edit, :update, :destroy]

  # GET /political_parties
  # GET /political_parties.json
  def index
    @political_parties = PoliticalParty.all
  end

  # GET /political_parties/1
  # GET /political_parties/1.json
  def show
  end

  # GET /political_parties/new
  def new
    @political_party = PoliticalParty.new
  end

  # GET /political_parties/1/edit
  def edit
  end

  # POST /political_parties
  # POST /political_parties.json
  def create
    @political_party = PoliticalParty.new(political_party_params)

    respond_to do |format|
      if @political_party.save
        format.html { redirect_to @political_party, notice: 'Political party was successfully created.' }
        format.json { render :show, status: :created, location: @political_party }
      else
        format.html { render :new }
        format.json { render json: @political_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /political_parties/1
  # PATCH/PUT /political_parties/1.json
  def update
    respond_to do |format|
      if @political_party.update(political_party_params)
        format.html { redirect_to @political_party, notice: 'Political party was successfully updated.' }
        format.json { render :show, status: :ok, location: @political_party }
      else
        format.html { render :edit }
        format.json { render json: @political_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /political_parties/1
  # DELETE /political_parties/1.json
  def destroy
    @political_party.destroy
    respond_to do |format|
      format.html { redirect_to political_parties_url, notice: 'Political party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_political_party
      @political_party = PoliticalParty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def political_party_params
      params.fetch(:political_party, {})
    end
end

app/helpers/political_parties_helper.rb
module PoliticalPartiesHelper
end

app/views/political_parties/_form.html.erb
<%= form_for(political_party) do |f| %>
  <% if political_party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(political_party.errors.count, "error") %> prohibited this political_party from being saved:</h2>

      <ul>
      <% political_party.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/political_parties/edit.html.erb
<h1>Editing Political Party</h1>

<%= render 'form', political_party: @political_party %>

<%= link_to 'Show', @political_party %> |
<%= link_to 'Back', political_parties_path %>

app/views/political_parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Political Parties</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @political_parties.each do |political_party| %>
      <tr>
        <td><%= link_to 'Show', political_party %></td>
        <td><%= link_to 'Edit', edit_political_party_path(political_party) %></td>
        <td><%= link_to 'Destroy', political_party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Political Party', new_political_party_path %>

app/views/political_parties/new.html.erb
<h1>New Political Party</h1>

<%= render 'form', political_party: @political_party %>

<%= link_to 'Back', political_parties_path %>

app/views/political_parties/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_political_party_path(@political_party) %> |
<%= link_to 'Back', political_parties_path %>