config/routes.rb
Rails.application.routes.draw do
  resources :politicians
  resources :political_parties
  resources :states
  resources :assembly_constituencies
  resources :loksabha_constituencies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/loksabha_constituencies_controller.rb
class LoksabhaConstituenciesController < ApplicationController
  before_action :set_loksabha_constituency, only: [:show, :edit, :update, :destroy]

  # GET /loksabha_constituencies
  # GET /loksabha_constituencies.json
  def index
    @loksabha_constituencies = LoksabhaConstituency.all
  end

  # GET /loksabha_constituencies/1
  # GET /loksabha_constituencies/1.json
  def show
  end

  # GET /loksabha_constituencies/new
  def new
    @loksabha_constituency = LoksabhaConstituency.new
  end

  # GET /loksabha_constituencies/1/edit
  def edit
  end

  # POST /loksabha_constituencies
  # POST /loksabha_constituencies.json
  def create
    @loksabha_constituency = LoksabhaConstituency.new(loksabha_constituency_params)

    respond_to do |format|
      if @loksabha_constituency.save
        format.html { redirect_to @loksabha_constituency, notice: 'Loksabha constituency was successfully created.' }
        format.json { render :show, status: :created, location: @loksabha_constituency }
      else
        format.html { render :new }
        format.json { render json: @loksabha_constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loksabha_constituencies/1
  # PATCH/PUT /loksabha_constituencies/1.json
  def update
    respond_to do |format|
      if @loksabha_constituency.update(loksabha_constituency_params)
        format.html { redirect_to @loksabha_constituency, notice: 'Loksabha constituency was successfully updated.' }
        format.json { render :show, status: :ok, location: @loksabha_constituency }
      else
        format.html { render :edit }
        format.json { render json: @loksabha_constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loksabha_constituencies/1
  # DELETE /loksabha_constituencies/1.json
  def destroy
    @loksabha_constituency.destroy
    respond_to do |format|
      format.html { redirect_to loksabha_constituencies_url, notice: 'Loksabha constituency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loksabha_constituency
      @loksabha_constituency = LoksabhaConstituency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loksabha_constituency_params
      params.fetch(:loksabha_constituency, {})
    end
end

app/helpers/loksabha_constituencies_helper.rb
module LoksabhaConstituenciesHelper
end

app/views/loksabha_constituencies/_form.html.erb
<%= form_for(loksabha_constituency) do |f| %>
  <% if loksabha_constituency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loksabha_constituency.errors.count, "error") %> prohibited this loksabha_constituency from being saved:</h2>

      <ul>
      <% loksabha_constituency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loksabha_constituencies/edit.html.erb
<h1>Editing Loksabha Constituency</h1>

<%= render 'form', loksabha_constituency: @loksabha_constituency %>

<%= link_to 'Show', @loksabha_constituency %> |
<%= link_to 'Back', loksabha_constituencies_path %>

app/views/loksabha_constituencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loksabha Constituencies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loksabha_constituencies.each do |loksabha_constituency| %>
      <tr>
        <td><%= link_to 'Show', loksabha_constituency %></td>
        <td><%= link_to 'Edit', edit_loksabha_constituency_path(loksabha_constituency) %></td>
        <td><%= link_to 'Destroy', loksabha_constituency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loksabha Constituency', new_loksabha_constituency_path %>

app/views/loksabha_constituencies/new.html.erb
<h1>New Loksabha Constituency</h1>

<%= render 'form', loksabha_constituency: @loksabha_constituency %>

<%= link_to 'Back', loksabha_constituencies_path %>

app/views/loksabha_constituencies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_loksabha_constituency_path(@loksabha_constituency) %> |
<%= link_to 'Back', loksabha_constituencies_path %>